#!/bin/sh

logfile=/home/mike/var/log/lvmscrub.log
lockfile=/home/mike/var/log/lvmscrub.pid

exec 9>>"${lockfile}"
flock -n 9 || exit 1
echo $$ >&9
trap "rm -f ${lockfile}; exit" INT TERM EXIT

set -e
[ -x "/usr/bin/sendmail" ] || {
	exec >"$logfile" 2>&1
	chown mike.mike "$logfile"
	echo -n "$0: Initiating check scrub on "
	date
}

[ "`id -u`" -eq "0" ] || {
	echo "$0: Error: must be root"
	exit 1
}

echo "Pre-scrub status"
lvs -o name,lv_attr,lv_health_status,raid_sync_action,sync_percent,raid_mismatch_count seiko/shared

if lvs --rows -o raid_sync_action seiko/shared | grep 'idle'; then
	echo "Requesting scrub."
	lvchange --syncaction check seiko/shared 
else
	echo "VG is not idle. Will not re-request scrub."
fi
